### ISSUE TITLE
咋用啊

### ISSUE THREAD

**Issue by ScrH0052** [MaxChang3/hexo-markmap#1]
是在博客的文件夹安装然后在markdown中使用吗？
为啥我在markdown中写报错 'unknown block tag: markmap'

**Comment by ScrH0052** [comment]
非常感谢回答，昨天咋试都不行，今天却啥问题都没了，有点神奇，明明啥都没动

**Comment by MaxChang3** [comment]
> 非常感谢回答，昨天咋试都不行，今天却啥问题都没了，有点神奇，明明啥都没动
> 
> 

唔 好的哈 估计重启hexo后载入出插件了。
