### ISSUE TITLE
进入文章界面后，必须要点刷新才能显示脑图

### ISSUE THREAD

**Issue by GalensGan** [MaxChang3/hexo-markmap#10]
作者你好！我用的是 NEXT 模板，`clean` 后再 `generate`，然后发布，发现打开文章时，不会显示脑图，必须要点一下刷新才行，请问这是什么原因导致的呢？
链接：https://galens.uamazing.cn/posts/2022/1C9ATGS.html

**Comment by MaxChang3** [comment]
很奇怪。我第一次点开你提供的链接的时候，脑图是正常显示的。 然后呢，我又从首页打开文章，这时候复现了你所说的问题。
这时候会发现 markmap 的相关库未能正确加载。
<img width="718" alt="image" src="https://user-images.githubusercontent.com/36927158/168477709-3c4ee21c-8281-4946-8dea-173f0e0477fc.png">

初步判定似乎和 `pjax` 有关？ 能否尝试关闭 pjax 看看是否仍然存在该问题？

另外我在本地也搭了一个 next 6.0 的环境，并没有复现此问题。

**Comment by GalensGan** [comment]
我在本地试了下，关闭 pjax 后，每次进入文章时会加载脑图了，但是在首页中还是不会显示脑图。
虽然关闭 pjax 有一定作用，但是关闭后，整个博客的体验都下降了，因为关闭后不能实现局部更新。

我使用的是 [hexo-theme-next v8.11.1](https://github.com/next-theme/hexo-theme-next/releases/tag/v8.11.1) 这个主题。

**Comment by GalensGan** [comment]
我在没有显示的界面输入 markmap，显示是存在值的，但是还是不显示：
![image](https://user-images.githubusercontent.com/45629076/168498510-7fb8abbd-fcd2-4039-81ed-c52d905aa6ef.png)

**Comment by MaxChang3** [comment]
> 我在没有显示的界面输入 markmap，显示是存在值的，但是还是不显示： ![image](https://user-images.githubusercontent.com/45629076/168498510-7fb8abbd-fcd2-4039-81ed-c52d905aa6ef.png)

如果我强制刷新页面，并从首页初次进入该界面，是无法调用 markmap 的。
那目前看就是 pjax 的问题了。 首页无法加载可能和样式和脚本注入点有关系。
我研究下有没有比较好的解决方案。

**Comment by MaxChang3** [comment]
你好，我尝试了下如下修改，在 next 8.11.1 开启 pjax 后可以正常载入，你这边试下有没有问题。

node_modules/hexo-markmap/index.js
42 行
```javascript
    <script data-pjax>
        document.querySelectorAll('.markmap-container>svg').forEach(mindmap => {
          markmap.Markmap.create(mindmap, null, JSON.parse(mindmap.getAttribute('data')))
        })
    </script>
```
即在最后一个 script 标签下增加 `data-pjax`

**Comment by GalensGan** [comment]
还是不行，调试窗口中提示：
```
VM97:1 Uncaught ReferenceError: markmap is not defined
    at <anonymous>:1:89
    at NodeList.forEach (<anonymous>)
    at <anonymous>:1:54
    at pjax.min.js:1
    at NodeList.forEach (<anonymous>)
    at Pjax.executeScripts (pjax.min.js:1)
    at HTMLDocument.<anonymous> (pjax.js:18)
    at Xa.h (AdGuard Popup Blocker.user.js:482)
    at nc (AdGuard Popup Blocker.user.js:500)
    at eval (AdGuard Popup Blocker.user.js:488)
```

**Comment by GalensGan** [comment]
现在的状态是这样的：
1. 直接进文章页面，可以显示
2. 先打开首页，再从首页进文章页，不显示
3. 从首页进文章页后，刷新，文章页显示，回到首页，首页不显示，然后从首页进入到文章页，文章页显示。
4. 当首页不显示时，在首页刷新后，再进入文章页，不显示

**Comment by MaxChang3** [comment]
> 作者你好！我用的是 NEXT 模板，`clean` 后再 `generate`，然后发布，发现打开文章时，不会显示脑图，必须要点一下刷新才行，请问这是什么原因导致的呢？

还是和 pjax 的加载机制有关。根据我本地的测试，首页的 markmap 的相关引入会正常载入。 但是在你的首页并没有出现。 所以在首页进入不会显示。而运行 markmap 则会提示未定义。  也许能通过判断一下再动态加载解决。
能否提供下 next 的配置文件和安装的其他插件列表？

**Comment by MaxChang3** [comment]
> 现在的状态是这样的：
> 
> 1. 直接进文章页面，可以显示
> 2. 先打开首页，再从首页进文章页，不显示
> 3. 从首页进文章页后，刷新，文章页显示，回到首页，首页不显示，然后从首页进入到文章页，文章页显示。
> 4. 当首页不显示时，在首页刷新后，再进入文章页，不显示


还是和 pjax 的加载机制有关。根据我本地的测试，首页的 markmap 的相关引入会正常载入。 但是在你的首页并没有出现。 所以在首页进入不会显示。而运行 markmap 则会提示未定义。  也许能通过判断一下再动态加载解决。
能否提供下 next 的配置文件和安装的其他插件列表？

**Comment by GalensGan** [comment]
这是配置文件，其中 data 里面是我自定义的样式
[hexo-site.zip](https://github.com/MaxChang3/hexo-markmap/files/8696906/hexo-site.zip)

**Comment by MaxChang3** [comment]
[blog.zip](https://github.com/MaxChang3/hexo-markmap/files/8696992/blog.zip)

好奇怪，我原样按你的配置过去的，然后就是对 `hexo-markmap` 进行了上述修改，除去删除了 `hexo-submit-urls-to-search-engine` （这边运行有报错）之外其他都是一致的，这边本地测试都是正常的（hexo s 与 hexo g）。

**Comment by GalensGan** [comment]
我用你的包运行了下，也不行，第一次进去可以，再点一次首页就消失了

**Comment by GalensGan** [comment]
这是操作录屏，希望有些帮助：
https://user-images.githubusercontent.com/45629076/168517007-e097f716-122f-4b5b-9a56-de1cc5d024ea.mp4

**Comment by MaxChang3** [comment]
但是还是感觉好奇怪这个为啥还会有差异呢，有机会再一下吧。
