### ISSUE TITLE
在生成的分页数据中，没有包含 markmap 脚本，导致在首页无法显示

### ISSUE THREAD

**Issue by GalensGan** [MaxChang3/hexo-markmap#12]
heox 会预先生成静态的分页数据，我发现当有很多文章时，在分页的html里不会包含 markmap 相关的脚本，导致无法加载markup。
见文件 516 行
[index.zip](https://github.com/MaxChang3/hexo-markmap/files/8704183/index.zip)

**Comment by MaxChang3** [comment]
因为首页并没有注入 markmap 相关脚本。 而有部分首页能注入成功的原因大概是内容较短的时候把 script 标签和正文一起截断到首页里了。 我稍后补充一个在首页插入 markmap 脚本的选项。

**Comment by MaxChang3** [comment]
因为首页并没有注入 markmap 相关脚本。 而有部分首页能注入成功的原因大概是内容较短的时候把 script 标签和正文一起截断到首页里了。 我稍后补充一个在首页插入 markmap 脚本的选项。

**Comment by MaxChang3** [comment]
多个文章分页，markmap 出现在简介中的情况，我本地环境测试的结果还是与你的情况不同的，但也是 bug，表现为：如果存在多个 markmap 在首页的简介中出现，会反复被截取到 markmap 的生成代码，因此会重复运行生成多个 markmap。 

所以我修改了下，你试试这个行不行：
https://github.com/MaxChang3/hexo-markmap/tree/feat-innerdata-using-filter

解决思路是，正常在 `</body>` 前插入，而不是使用原有的 `after_post_render` 追加到 content 上。

一开始想使用 `hexo.extend.injector` 插入到 `body_end` 实现，但是这样无法获取页面数据来判断是否启用了 markmap 。

所以我用 `hexo.extend.filter.register('after_render:html')`  在全局可能会出现 markmap 的位置都插入 script，这样就防止了重复插入，而首页也因此有个 markmap 相关脚本，所以理论上来讲能正常调用。

**Comment by GalensGan** [comment]
我测试了，这个方式没问题。
更新了下 pjax 初始化的模块 #13
