### ISSUE TITLE
prism css 其它地方已经加载了的时候，是配置和其它地方一样的prism css地址还是有更好的配置方法？

### ISSUE THREAD

**Issue by appotry** [MaxChang3/hexo-markmap#25]
如题 prism css 其它地方已经加载了的时候，是配置其它地方一样的prism css地址还是有更好的配置方法？

**Comment by appotry** [comment]
不同版本的prism css一起加载 会导致一些奇怪的bug

**Comment by MaxChang3** [comment]
我再加一个 prism css 的开关怎么样。 这样如果你其他地方已经加载就可以用其他的了？

**Comment by appotry** [comment]
> 我再加一个 prism css 的开关怎么样。 这样如果你其他地方已经加载就可以用其他的了？

这是一个可行的解决方法

或者判断prism_css用户配置为null，就默认用户其它地方已经加载了prism css

**Comment by MaxChang3** [comment]
ok 我等下修改下，因为当时 katex 和 prism 一块加进去的直接 把他们都弄成 katex 选项为 true 的时候默认插入了。其实不是一回事。

**Comment by MaxChang3** [comment]
已经添加。 #26
