### ISSUE TITLE
设想：关于插件的想法

### ISSUE THREAD

**Issue by zuoer96** [MaxChang3/hexo-markmap#29]
用了一段时间了，我主要是用在站点的文档导航，感觉挺好的。谢谢作者的贡献。
然后就是一些关于插件的建议或者说想法

1. 如果支持热点统计(访问点击哪个节点)，或者热点排序应该会挺好的。不过要对接后端估计是个问题
2. 单节点可以自定义是否展开
3. 鼠标滚轮进入图的会放大和缩小，但是因为没有明显的界限，所以我经常因为想滚动屏幕而缩小图了(一瞬间会让人有点错愕感)。

-   不过对于这点也没有好的建议。感觉加个边框，配合框内滚轮放大缩小的提示什么的可能会更好？
-   现在的可以用Ctrl+鼠标滚轮放大缩小，不过放大/缩小的比例不够精细。如果更精细的话，可能在区域内禁用鼠标滚轮会更好?
-   又测试了下，单独按住滚轮，可以控制精细的放大/缩小，就是比较费劲。这个应该我的鼠标也占一部分原因。。

4. 组合效果：支持正常1倍的固定大小+禁止缩放+不可移动+自定义节点的展开收起

**Comment by MaxChang3** [comment]
非常好的想法，但是这方面的话应该提给 [markmap](https://github.com/gera2ld/markmap) 那边比较准确一些。

因为这边实际上就是对 markmap 各个 package 的调用。 所有实际功能实现都是由 markmap 那边去完成的。

有些功能可能需要这边配合。 比如第二条，自定义单节点的展开，如果 markmap 那边有接口这边可以配合提供配置项。

而其他方面就要去找那边作者处理了。 : )
