### ISSUE TITLE
如何设置根主题上的文字？

### ISSUE THREAD

**Issue by lblk** [MaxChang3/hexo-markmap#3]
希望有个demo

**Comment by MaxChang3** [comment]
```markdown
# 根结点

## 子节点1
 - qwq
 - qaq
## 子节点2
 - qwq
 - qaq
```
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/36927158/153209429-0988df3c-4732-4e5d-b075-e0e895d0983d.png">

**Comment by lblk** [comment]
谢谢
