### ISSUE TITLE
标签包裹的 markdown 会在编辑器预览中被渲染，易与正文混淆且影响版面

### ISSUE THREAD

**Issue by kebuAAA** [MaxChang3/hexo-markmap#36]
外挂标签引入之后在不支持hexo的md查看器中会看到{% markmap 800px 1%} {% endmarkmap %}包裹的内容，这样如果思维导图比较大的话会比较烦，我觉得可以考虑在包裹内容内加md专属的注释符号把内容注释掉来使用这个功能，这样就能实现本地预览器看不到包裹的内容而又可以在博客正常生成思维导图的效果，一个小小的建议。
因为我是想使用这个插件来做一个目录的，这样如果目录层级多的话会给本地预览带来很多不便，我提的这个建议其实只需稍微变更一下匹配规则就可以更完美一些。

**Comment by MaxChang3** [comment]
你好！你说的问题确实存在，不过鉴于可能存在与之相反的需求，可以增加该功能并默认配置为关闭。

不过 “md 专属的注释符号”指的是？

markdown 标准似乎没有规定注释符号🤔。

**Comment by kebuAAA** [comment]
这个问题我昨天找到一个解决方案是通过iframe引入html解决掉了，标准的Markdown没有注释符号的话那我说的可能有待考虑，我使用的Vscode是使用标记的，不过我的问题已经解决了，谢谢作者的及时回复！

**Comment by kebuAAA** [comment]
> 你好！你说的问题确实存在，不过鉴于可能存在与之相反的需求，可以增加该功能并默认配置为关闭。
> 
> 不过 “md 专属的注释符号”指的是？
> 
> markdown 标准似乎没有规定注释符号🤔。

这个问题我昨天找到一个解决方案是通过iframe引入html解决掉了，标准的Markdown没有注释符号的话那我说的可能有待考虑，我使用的Vscode是使用标记的，不过我的问题已经解决了，谢谢作者的及时回复！
