### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by zuoer96** [MaxChang3/hexo-markmap#43]
报错信息：uncaught DOMException: Failed to read the 'value' property from 'SVGLength': Could not resolve relative length.
版本："hexo-markmap": "^1.1.5",
报错图片：
<img src="https://cdn.jsdelivr.net/gh/zuoer96/CDN@master/issue/github/2023-04-05_21-26-25.jpg"/>

**Comment by zuoer96** [comment]
【问题复现】
尝试升级到 "hexo-markmap": "^1.1.6",  还是会报错

尝试关闭pjax，关闭后不会报错
开启pjax，第一次点击菜单，渲染正常，切换菜单，就会报这个错误

【配置】：
`config.next.yml`
pjax: true # false

`config.yml`
hexo_markmap:
  pjax: true # 默认值：false

**Comment by MaxChang3** [comment]
你好，能否提供可以访问的地址或者最小的复现。本地搭建 next 开启 pjax 下未发现该情况

**Comment by zuoer96** [comment]
> 你好，能否提供地址或最小的复现代码。本地搭建 next 开启 pjax 下未发现该情况

https://nbchen.com/  点击 心有猛虎嗅蔷薇 菜单，再点击其他可以复现

**Comment by MaxChang3** [comment]
本地复现成功。问题应该是 d3-zoom 保留了含有 markmap 页面的状态（元素）数据，切换到无相关元素的时候会报错。不过不影响使用。 解决思路应该是在 pjax 切换时清除相关数据。我研究一下。


---

Translation:

Successfully reproduced locally. The problem should be that d3-zoom retains the state (element) data containing the markmap page by pjax, and an error will occur when switching to a page without related elements. However, this does not affect use. The solution should be to clear the relevant data when switching pjax. I’ll look into it.”

**Comment by MaxChang3** [comment]
autofit 的 observer 在 pjax 触发后应该刷新一下。我修复下

**Comment by MaxChang3** [comment]
@zuoer96  已经修复，请更新 `1.1.7` 尝试

**Comment by zuoer96** [comment]
已升级 没有报错了 谢谢
