### ISSUE TITLE
初始化默认查看时候可以调大小么

### ISSUE THREAD

**Issue by zenkinwin** [MaxChang3/hexo-markmap#6]
1. 比较宽使得字体比较小，怎样默认调大呢？
2. 多行字体时候行高不够，调大后出现超出了彩色线。
![image](https://user-images.githubusercontent.com/5841364/165070421-5613931f-0d8c-400e-81e8-f80edb3568a9.png)

**Comment by MaxChang3** [comment]
你好。
1. 可以调大参数中的尺寸，这样 markmap 区域会变大，字体也会相应变大。 单独调节字体大小 markmap 上游未支持。
2. 多行的时候行高不够？这句没完全理解，可以发下事例 markdown 么？（我感觉可能还是 markmap 的问题）
<img width="711" alt="image" src="https://user-images.githubusercontent.com/36927158/165202774-be8eeac1-0af2-47cc-8e25-f71dcd92f3cc.png">
<del>所以都怪 markmap( bushi</del>
