### ISSUE TITLE
页面出现 undefined 无法显示内容

### ISSUE THREAD

**Issue by jycoast** [MaxChang3/hexo-markmap#7]
![image](https://user-images.githubusercontent.com/42469825/166150255-8114a7c2-7c58-4cb5-a5d3-97beb704ceb5.png)

如题，可以看看吗 @MaxChang3

**Comment by MaxChang3** [comment]
不好意思，之前没注意这个细节，忘了锁定引入库(markmap-view)的版本了，更新最新版本后清理下缓存即可。
---
Sorry, I forgot to lock the version of lib we used(markmap-view), update the latest version and clean the cache to fix it.

https://github.com/gera2ld/markmap/commit/963b0f47f78be88a06ff50bed97a7ce0597cf392
https://github.com/MaxChang3/hexo-markmap/commit/ee6b7ed08b36be9d4f66b964ee0a938786bafba4
